# Generated by Django 6.1.1 on 2026-09-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(help_text="Short headline, e.g. 'Aligned with PMBOK 7th Edition & Agile Practice Guide'", max_length=255)),
                ('overview', models.TextField(help_text='Comprehensive course summary focusing on field delivery.')),
                ('contact_hours', models.PositiveIntegerField(default=35, help_text='Accredited PMI contact hours or PDUs.')),
                ('duration_weeks', models.PositiveIntegerField(default=8, help_text='Length of cohort in weeks.')),
                ('delivery_mode', models.CharField(choices=[('WEEKEND', 'Weekend Intensive'), ('EVENING', 'Weekday Evening Track'), ('HYBRID', 'Hybrid (In-person & Virtual)'), ('ONLINE', 'Instructor-Led Virtual')], default='WEEKEND', max_length=20)),
                ('schedule_details', models.CharField(help_text="e.g. 'Saturdays: 9:00 AM – 3:00 PM GMT'", max_length=150)),
                ('deliverables', models.TextField(help_text="Core takeaways, one per line (e.g. '35 Approved PMI Contact Hours', 'EVM Spreadsheet Models').")),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Tuition fee.', max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.category')),
            ],
            options={
                'ordering': ['-is_featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_code', models.CharField(help_text="e.g. 'PMP-OCT-2026' or 'Cohort 12'", max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_seats', models.PositiveIntegerField(default=25)),
                ('is_open_for_enrollment', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='courses.course')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='WhatsApp or mobile number', max_length=30)),
                ('organization', models.CharField(blank=True, help_text='Current employer or client organization', max_length=150)),
                ('experience_level', models.CharField(choices=[('0-2', '0 - 2 Years (Early Career)'), ('3-5', '3 - 5 Years (Supervisor / Mid-Level)'), ('5-10', '5 - 10 Years (Senior Manager / Lead)'), ('10+', '10+ Years (Director / Executive)')], default='3-5', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONTACTED', 'Candidate Contacted'), ('ADMITTED', 'Admitted to Cohort'), ('COMPLETED', 'Graduated'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Deposit / Partial Payment'), ('PAID', 'Fully Paid'), ('SPONSORED', 'Corporate Sponsored')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal coordinator notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='courses.cohort')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
