# Generated by Django 6.1.1 on 2026-10-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_contactinquiry_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, help_text='Unique tracking reference code (e.g., PF-ASK-8F3A29)', max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, help_text='Inquiry subject or topic', max_length=200)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, help_text='Latest response provided by Director awuah or Directorate staff')),
                ('status', models.CharField(choices=[('PENDING', 'Under Review'), ('ANSWERED', 'Answered')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional syllabus track associated with the question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_tickets', to='courses.course')),
            ],
            options={
                'verbose_name': 'Question Ticket',
                'verbose_name_plural': 'Question Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('VISITOR', 'Visitor / Candidate'), ('DIRECTOR', 'Director awuah')], default='VISITOR', max_length=15)),
                ('sender_name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(help_text='Inquiry thread this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='courses.questionticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
