# Generated by Django 6.1.1 on 2026-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_questionticket_ticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('fundamentals', 'Fundamentals'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='fundamentals', help_text='Course tier: Fundamentals, Intermediate, or Advanced', max_length=20),
        ),
    ]
